define e = Character("Eileen")
define mary = Character("Marianna", color="ffffff")
define r = Character("Ryoshu", color="ffffff")
define mc = Character(None)
define uncle = Character("Uncle", color="ffffff")